spring:
  application:
    name: tydic-xinjiang-integration
  datasource:
      druid:
        stat-view-servlet:
          login-username: tydic
          login-password: tydic2018
        postgis:
          # url: jdbc:postgresql://192.168.128.108:5432/cem_gis
          url: jdbc:postgresql://172.16.30.95:5432/cem_gis
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: postgres
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          # 配置初始化大小、最小、最大
          initial-size: 5
          max-active: 20
          min-idle: 5
          # 配置获取连接等待超时的时间
          max-wait: 60000
          validationQuery: select 1
          testOnBorrow: true

server:
  port: 8084
